### ISSUE TITLE
Im stuck on the world loading screen. It dosent progress.

### ISSUE THREAD

**Issue by DarthKodar** [xandergos/terrain-diffusion-mc#38]
hey, so i have been following all the steps. I have windows 11 and an Nvidia gpu.  the CUDNN path is like this: C:\Program Files\NVIDIA\CUDNN\v9.21\bin\12.9\x64 and it contains cudnn64_9.dll. The cuda path is C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin and it contains cudart64_12.dll. I have checked my path, and they are both under system variables. The mod version i have downloaded was for 1.21.11. I use the V2.0.4 version where "terrain-diffusion-mc-2.0.4+1.21.11.jar" is what i downloaded and added to the mods folder. I also downloaded the other two assets but i have no idea what they are. I have really tried for many hours but i dont know how to get it to work. 

Thank you for your help

**Comment by xandergos** [comment]
did you *edit* the system "path" variable (the correct approach)? Or did you add new environment variables? I would recommend following [the link in the setup instructions](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

**Comment by DarthKodar** [comment]
The path for CUDNN didn't show up so I clicked on new there. and I got 3 different paths for CUDA. I deleted the 2 that weren't on the instruction page. The 3rd one I had to edit cause it wasn't entirely correct either.  But if I made a mistake. Do I have to delete everything and start over again?

**Comment by ThatDamnWittyWhizHard** [comment]
Is this issue resolved?

**Comment by DarthKodar** [comment]
I have been unable to make it work yet. But for the last 2 weeks my ive been away from my pc so cant test right now. I will try to delete everything and start again from zero, and do everything you said. Ill report back if it works then

**Comment by ThatDamnWittyWhizHard** [comment]
You should try the Windows version first and check if everything is working. Then reinstall the CUDA version properly. Let us know if you’re still facing issues.

**Comment by DarthKodar** [comment]
I have now downloaded from Modrinth, now it works!
