### ISSUE TITLE
World generation stuck at 0% with CUDA

### ISSUE THREAD

**Issue by trueandrew1** [xandergos/terrain-diffusion-mc#98]
I'm using Sinytra Connector and Forgified Fabric to use this mod in a NeoForge modpack. Using the CUDA version, it gets stuck at 0% generation. When running `where cudnn64_9.dll` I get `C:\Program Files\NVIDIA\CUDNN\v9.21\bin\12.9\x64\cudnn64_9.dll` and `where cudart64_12.dll` gives `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin\cudart64_12.dll`, so I think I set the PATH variables correctly.

I'm using it in a modpack, could there be any incompatibilities causing this issue?

My windows version is 25H2 OS Build 26200.8246

My NVIDIA graphics drivers were just updated.

Here is the log after I force close it after a minute or so, any help would be greatly appreciated!!

(The other versions don't work either)

<img width="632" height="361" alt="Image" src="https://github.com/user-attachments/assets/89ffd9fc-9ff4-41dd-bc6b-7248358d795e" />

[latest.log](https://github.com/user-attachments/files/27223837/latest.log)

**Comment by trueandrew1** [comment]
Okay so update, I tried it on a fabric only instance. The CUDA version won't even open, but the windows version opens and then crashes on worldgen. Here's the log: https://mclo.gs/nLefNFi

So I think that it isn't related to Sinytra... now I am thoroughly confused.

**Comment by Arcanum3000** [comment]
This suggests an Oracle Java compatibility problem.  https://github.com/microsoft/onnxruntime/issues/24287

Can you use the Adoptium Temurin version 21 JRE?  Prism Launcher makes it easy to set up, and it works correctly in my experience.

Setting that aside, piling additional biome mods on top of Terrain Diffusion will likely not work due to TD completely hijacking Minecraft's mod placement.

**Comment by trueandrew1** [comment]
That fixed the problem on both versions! Thank you so much! Not sure why adoptium temurin worked but my normal java 21 doesnt, but I'm not complaining

If it doesnt mesh with the biome mods i'll disable those, I'd much rather have the cool terrain lol.
